services:
  main:
    image: node
    working_dir: "/mainservice"
    command: /bin/bash start.sh
    volumes:
      - ./mainservice:/mainservice
    env_file:
      - main.env
    environment:
      - REDIS_URL=redis://redis:6379
      - APRILTAG_URL=http://apriltag:8000
  redis:
    image: redis
    command: redis-server
    volumes:
      - redisvolume:/data
  apriltag:
    build: apriltagservice
    env_file:
      - main.env
    command: /usr/local/bin/fastapi dev --host 0.0.0.0
    volumes:
      - ./apriltagservice:/apriltagservice
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    env_file:
      - minio.env
    volumes:
      - miniovolume:/data
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf

volumes:
  redisvolume:
  miniovolume:
