FROM node:23.10.0-bookworm
WORKDIR /mainservice
ADD package-lock.json .
ADD package.json .
RUN npm ci
ADD . /mainservice
# Fill with your environment variable data
ENV S3_ENDPOINT=http://minio.getcrossview.com
ENV S3_ENDPOINT_INTERNAL=http://minio:9000
ENV S3_REGION=us-east-1
ENV S3_ACCESS_KEY_ID=aaaaaaaaaaaaaaaaaaaa
ENV S3_SECRET_ACCESS_KEY=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
ENV S3_BUCKET=calibrations
ENV REDIS_URL=redis://redis:6379
ENV APRILTAG_URL=http://apriltag:8000

RUN npm run build
CMD ["npm", "run", "start"]